Repository Asset-management-service/frontend, pull requests merged in 2022-04, with the labels that each got.

#75 Login UI 및 로직 수정
  src/components/Login/LoginModal.js
  src/components/Login/OauthRedirect.js
  src/components/Login/SocialLogin.js
  src/lib/api/auth.js
  src/mocks/handlers.js
  src/modules/login.js
  src/pages/Home.js
  src/pages/Login.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI, 📬 API, 😎 Mock

#76 Common Component UI 수정
  src/components/common/Button.js
  src/components/common/ComboBox.js
  src/components/common/DropMenu.js
  src/components/common/FormInput.js
  src/components/common/Header/NavLinks.js
  src/components/common/Header/UserLinks.js
  src/components/common/Header/index.js
  src/components/common/Loading.js
  src/components/common/Modal.js
Labels: 🔨 Task, ♻️ Refactor

#77 불필요한 파일 삭제
  src/constants/assetCatetory.js
  src/constants/stockColor.js
  src/pages/MyPage.js
  src/pages/MySubPage.js
  src/pages/ResetPwd.js
Labels: ♻️ Refactor

#78 chrome extension 관련 에러 수정
  public/index.html
  public/manifest.json
Labels: 🐞 BugFix

#90 게시글 목록 및 상세 UI
  src/App.js
  src/components/Community/BoardDetail.js
  src/components/Community/BoardItem.js
  src/components/Community/BoardList.js
  src/components/Community/CommentForm.js
  src/components/Community/CommentItem.js
  src/components/Community/CommentList.js
  src/components/common/SideBar.js
  src/constants/index.js
  src/index.scss
  src/pages/CommunityPage/CommunityDetailPage.js
  src/pages/CommunityPage/CommunityListPage.js
  src/pages/CommunityPage/CommunitySubPage.js
  src/pages/CommunityPage/CommunityWritePage.js
  src/pages/CommunityPage/index.js
Labels: 🔨 Task, 💄 UI

#63 개인정보 변경 UI 구현
  src/components/MyPage/PersonalInfoChangeForm.js
Labels: 🔨 Task, 💄 UI

#105 Social Login API 로직 수정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Login/OauthRedirect.js
  src/components/Login/SocialLogin.js
  src/components/common/Header/UserLinks.js
  src/components/common/Header/index.js
  src/modules/login.js
  src/pages/MyPage/MySubPage.js
  src/pages/MyPage/index.js
Labels: 🔨 Task, ♻️ Refactor, 📬 API, 📦️Package

#106 FormInput Notification Component 디자인 수정
  src/components/common/FormInput.js
  src/components/common/Header/Notification.js
Labels: 🔨 Task, 💄 UI

#107 api 모킹 코드 주석 처리
  src/index.js
  src/mocks/handlers.js
Labels: 📬 API, 😎 Mock

#108 게시물 작성 UI
  src/components/common/Editor.js
  src/index.scss
  src/pages/CommunityPage/CommunityWritePage.js
Labels: 🔨 Task, 💄 UI

#109 가계부 페이지 전체 UI 구현
  src/pages/MoneyBook.js
Labels: ⛰️ Epic

#110 마이페이지 UI 합침
  src/components/MyPage/PrivateInfo.js
  src/components/MyPage/WithDraw.js
  src/pages/MyPage/MySubPage.js
Labels: 🔨 Task, ♻️ Refactor, 💄 UI

#113 프록시 변경
  package-lock.json
  package.json
Labels: 📦️Package

#114 Header Component 디자인 수정
  src/components/common/Header/Logo.js
  src/components/common/Header/index.js
  src/components/common/SideBar.js
Labels: 🔨 Task, 💄 UI

#115 MyPage Sidebar 디자인 수정
  src/components/MyPage/MyBadgeList.js
  src/components/MyPage/SideBar.js
  src/pages/MyPage/index.js
Labels: 🔨 Task, 💄 UI

#116 커뮤니티 페이지에 login 권한 로직 추가
  src/components/Community/CommentItem.js
  src/components/Community/CommentList.js
  src/components/common/Modal.js
  src/components/common/NotLogin.js
  src/hooks/useNotLogin.js
  src/pages/CommunityPage/CommunityListPage.js
Labels: ✨ Feature, 🔨 Task

#117 댓글 input textarea로 변경
  src/components/Community/CommentForm.js
  src/components/common/TextArea.js
Labels: 🔨 Task, 💄 UI

#118 게시글 작성 UI 수정
  src/components/Community/ImagePreview.js
  src/components/common/Editor.js
  src/index.scss
  src/pages/CommunityPage/CommunitySubPage.js
Labels: 🔨 Task, 💄 UI

#119 이미지 업로드 기능 추가
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ✨ Feature, ⛰️ Epic

#120 소셜 로그인 링크 수정
  src/components/Login/SocialLogin.js
Labels: 🔨 Task, 📬 API

#122 가계부 페이지 import 코드 수정
  src/pages/MoneyBook.js
Labels: ⛰️ Epic

#123 menu 상수들을 constants/nav.js로 옮김
  src/components/Community/BoardDetail.js
  src/components/Community/CommentItem.js
  src/constants/nav.js
  src/pages/CommunityPage/index.js
  src/pages/MoneyBook.js
  src/pages/MyPage/index.js
Labels: ♻️ Refactor

#124 불필요한 코드 삭제
  src/components/Community/CommentForm.js
Labels: ♻️ Refactor

#126 마이페이지 UI 중 개인정보 UI 페이지 변경
  src/components/MyPage/PersonalInfoChangeForm.js
Labels: 🔨 Task, ♻️ Refactor

#129 게시물 작성 페이지에 redux 적용
  src/components/Community/BoardList.js
  src/components/Community/PostDetail.js
  src/components/Community/PostItem.js
  src/components/Community/PostList.js
  src/components/common/Editor.js
  src/components/common/ImagePreview.js
  src/components/common/WriteActionButtons.js
  src/containers/EditorContainer.js
  src/modules/index.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ⛰️ Epic, ♻️ Refactor

#130 커뮤니티 api 적용 밑작업
  src/components/Community/CommentForm.js
  src/components/Community/CommentItem.js
  src/components/Community/CommentList.js
  src/components/Community/PostDetail.js
  src/components/Community/PostDropMenu.js
  src/containers/CommentFormContainer.js
  src/containers/PostDetailContainer.js
  src/lib/api/post.js
  src/modules/comment.js
  src/pages/CommunityPage/CommunityDetailPage.js
  src/pages/CommunityPage/CommunityListPage.js
Labels: ✨ Feature, ⛰️ Epic, 📬 API

#132 머니로그 페이지 UI 구현
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogForm.js
  src/components/FinancialLedger/MoneyLogGuide.js
  src/components/common/Calender.js
  src/components/common/ComboBox.js
  src/components/common/DropMenu.js
  src/components/common/Editor.js
  src/components/common/FormInput.js
  src/components/common/Header/NavLinks.js
  src/components/common/Loading.js
  src/constants/calender.js
  src/constants/nav.js
  src/containers/CalenderContainer.js
  src/containers/MoneyLogContainer.js
  src/images/money-bag.png
  src/modules/calender.js
  src/pages/FinancialLedgerPage/FinancialLedgerSubPage.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
  src/pages/MoneyBook.js
Labels: 🔨 Task, 💄 UI

#133 수익 및 지출 관리 페이지 UI 구현
  src/components/FinancialLedger/HistoryForm.js
  src/components/FinancialLedger/HistoryMain.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/pages/FinancialLedgerPage/HistoryPage.js
Labels: 🔨 Task, 💄 UI

#134 수익 및 지출 관리 페이지에 redux 적용
  src/containers/HistoryFormContainer.js
  src/containers/HistoryMainContainer.js
  src/modules/history.js
  src/modules/index.js
Labels: ⛰️ Epic, ♻️ Refactor

#135 로그인 토큰 관련 로직 수정
  src/App.js
  src/components/Login/OauthRedirect.js
  src/components/common/Header/UserLinks.js
  src/containers/LoginFormContainer.js
  src/lib/api/auth.js
  src/modules/login.js
Labels: ⛰️ Epic, ♻️ Refactor

#137 Login Url 수정
  .env.development
  .env.production
  src/components/Login/SocialLogin.js
  src/constants/loginUrl.js
Labels: ⛰️ Epic, 📬 API

#138 header에 token 넣는 로직 추가
  src/components/Login/OauthRedirect.js
  src/components/common/Header/UserLinks.js
  src/lib/api/auth.js
Labels: ⛰️ Epic, 📬 API

#139 마이페이지에서 내가 쓴 글 및 댓글 api 적용
  src/components/MyPage/MyCommetItem.js
  src/components/MyPage/MyPostList.js
  src/components/MyPage/NoList.js
  src/components/common/DoubleCheckModal.js
  src/lib/api/user.js
  src/pages/MyPage/MySubPage.js
  src/pages/MyPage/index.js
Labels: ✨ Feature, 🔨 Task, 💄 UI, 📬 API

#140 새로고침해도 로그인 유지되는 로직 추가
  src/App.js
Labels: ♻️ Refactor

#141 게시물 작성 페이지에 api 적용
  src/containers/EditorContainer.js
  src/lib/api/post.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: 🔨 Task, 📬 API

#142 게시물 작성 관련 Editor, ImagePreview 컴포넌트 수정
  src/components/common/Editor.js
  src/components/common/ImagePreview.js
Labels: 🔨 Task, 💄 UI

#143 게시물 목록 페이지 api 적용
  src/components/Community/PostList.js
  src/constants/community.js
  src/constants/index.js
  src/pages/CommunityPage/CommunityListPage.js
  src/pages/CommunityPage/index.js
Labels: 🔨 Task, 📬 API

#144 게시물 상세 페이지 api 적용
  src/components/Community/CommentForm.js
  src/components/Community/CommentItem.js
  src/components/Community/CommentList.js
  src/components/Community/PostDetail.js
  src/components/Community/PostDropMenu.js
  src/containers/CommentFormContainer.js
  src/containers/PostDetailContainer.js
  src/lib/api/comment.js
  src/modules/comment.js
  src/pages/CommunityPage/CommunityDetailPage.js
  src/pages/CommunityPage/CommunitySubPage.js
Labels: 🔨 Task, 📬 API

#145 게시글 목록 아이템 디자인 수정
  src/components/Community/PostItem.js
Labels: 🔨 Task, 💄 UI

#146 마이페이지에 api 적용 완료
  src/components/MyPage/MyCommetItem.js
  src/components/MyPage/MyPostItem.js
  src/components/MyPage/MyPostList.js
  src/lib/api/user.js
Labels: 🔨 Task, 📬 API

#147 게시물 수정 api 적용
  src/components/Community/ImageList.js
  src/components/common/Editor.js
  src/components/common/ImagePreview.js
  src/containers/EditorContainer.js
  src/lib/api/post.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: 🔨 Task, 📬 API

#148 게시물 상세 페이지에 스크랩 api 적용
  src/components/Community/PostDropMenu.js
  src/containers/PostDetailContainer.js
Labels: 🔨 Task, 📬 API

#149 게시물 상세 페이지에 이미지 볼 수 있는 UI 추가
  src/components/Community/PostDetail.js
Labels: 🔨 Task, 💄 UI

#151 댓글 추가 api 반환값 이용하여 댓글 추가 로직 수정
  src/containers/CommentFormContainer.js
Labels: 🔨 Task, 📬 API

#128 가계부 설정 UI 구현
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/CategoryList.js
  src/components/FinancialLedger/InsertCategory.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/SetExpenseRatio.js
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/components/FinancialLedger/SettingListTitle.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/pages/FinancialLedgerPage/Setting.js
Labels: 🔨 Task, ♻️ Refactor, 💄 UI

#154 가계부 설정 UI에서 지출 비율 설정 수정
  src/components/FinancialLedger/SetExpenseRatio.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#155 FinancialLedgerSubpage에 SettingPage를 추가
  src/pages/FinancialLedgerPage/FinancialLedgerSubPage.js
  src/pages/FinancialLedgerPage/Setting.js
Labels: ⛰️ Epic, ♻️ Refactor

#156 커뮤니티 auth 로직 수정
  src/components/Community/PostItem.js
Labels: ♻️ Refactor

#157 커뮤니티 api 요청 수정
  src/lib/api/post.js
Labels: ♻️ Refactor, 📬 API

#158 달력 redux 초기 상태값 수정
  src/modules/calender.js
Labels: ♻️ Refactor

#159 수익지출관리 GET api 적용
  src/components/FinancialLedger/HistoryMain.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/lib/api/history.js
Labels: 🔨 Task, 📬 API

#161 가계부 auth 로직 수정
  src/pages/FinancialLedgerPage/index.js
Labels: ♻️ Refactor

#162 머니로그 UI에 자산 관리 목표 입력 UI 추가
  src/components/FinancialLedger/MoneyLogAssetGoal.js
  src/components/common/Calender.js
  src/containers/CalenderContainer.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
Labels: 🔨 Task, 💄 UI

#163 가계부 UI 변경
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/CategoryList.js
  src/components/FinancialLedger/InsertCategory.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#164 가계부 UI를 가운데 정렬
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/CategoryList.js
  src/components/FinancialLedger/InsertCategory.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#165 가계부 설정 api 적용 밑작업
  src/lib/api/setting.js
Labels: 🔨 Task, 📬 API

#166 가계부 UI 변경
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/CategoryList.js
  src/components/FinancialLedger/InsertCategory.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#168 수익지출 관리 페이지, 머니로그 페이지 UI 수정
  src/components/common/SideBar.js
  src/pages/FinancialLedgerPage/HistoryPage.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
  src/pages/FinancialLedgerPage/index.js
Labels: 🔨 Task, 💄 UI

#167 가계부 UI 변경
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#169 가계부 설정 페이지 redux 적용 및 api 적용
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/CategoryList.js
  src/components/FinancialLedger/InsertCategory.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/SetExpenseRatio.js
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/constants/category.js
  src/containers/BudgetContainer.js
  src/containers/CategoryContainer.js
  src/containers/ExpenseContainer.js
  src/modules/budget.js
  src/modules/category.js
  src/modules/expense.js
  src/pages/FinancialLedgerPage/SettingPage.js
  src/pages/FinancialLedgerPage/index.js
Labels: ⛰️ Epic, ♻️ Refactor, 📬 API

#170 가계부 수익 지출 내역 api 위치 변경
  src/components/FinancialLedger/HistoryMain.js
  src/containers/HistoryMainContainer.js
Labels: ⛰️ Epic, ♻️ Refactor

#171 가계부 설정 페이지 UI 수정
  src/components/FinancialLedger/StyledComponentInSetting.js
Labels: 🔨 Task, 💄 UI

#172 가계부 예산 설정 오류 수정
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/components/FinancialLedger/StyledComponentInSetting.js
Labels: 🐞 BugFix

#173 가계부 예산/지출비율 설정 로직 수정
  src/components/FinancialLedger/SetExpenseRatio.js
  src/containers/BudgetContainer.js
  src/containers/ExpenseContainer.js
  src/modules/expense.js
  src/pages/FinancialLedgerPage/index.js
Labels: ♻️ Refactor

#174 수익 지출 관리 페이지 api 적용
  src/components/FinancialLedger/HistoryForm.js
  src/components/FinancialLedger/HistoryMain.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/components/FinancialLedger/HistoryMainList.js
  src/components/common/ComboBox.js
  src/containers/HistoryFormContainer.js
  src/containers/HistoryMainContainer.js
  src/lib/api/history.js
  src/modules/history.js
Labels: 🔨 Task, 📬 API

#175 수익 지출 관리 페이지 GET api 오류 로직 수정
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/containers/HistoryMainContainer.js
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ♻️ Refactor

#176 가계부 수익 지출 관리 페이지 UI 수정
  src/components/FinancialLedger/HistoryMain.js
Labels: 🔨 Task, 💄 UI

#177 설정 페이지 alert 코드 수정
  src/pages/FinancialLedgerPage/SettingPage.js
Labels: ♻️ Refactor

#178 수익 지출 관리 페이지 UI 수정
  src/components/FinancialLedger/HistoryMain.js
Labels: 🔨 Task, 💄 UI

#179 불필요한 패키지 삭제 및 관련 코드 수정
  package-lock.json
  package.json
  src/index.js
  src/modules/index.js
Labels: ♻️ Refactor, 📦️Package

#181 설정 페이지 UI 수정
  src/components/FinancialLedger/CategoryItem.js
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/components/common/Modal.js
Labels: 🔨 Task, 💄 UI

#182 수익 지출 관리 페이지 UI 수정
  src/components/FinancialLedger/HistoryMain.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/components/FinancialLedger/HistoryMainList.js
Labels: 🔨 Task, 💄 UI

#183 Fix: 커뮤니티 상세 페이지 UI 오류 수정
  src/components/Community/PostDetail.js
Labels: 🐞 BugFix

#184 머니로그 페이지 api 적용 및 그에 따른 UI 변경
  src/components/Community/PostDetail.js
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogAssetGoal.js
  src/components/FinancialLedger/MoneyLogForm.js
  src/components/FinancialLedger/MoneyLogGuide.js
  src/components/common/Editor.js
  src/components/common/ImageList.js
  src/containers/MoneyLogContainer.js
  src/lib/api/moneylog.js
  src/lib/api/setting.js
Labels: 🔨 Task, ♻️ Refactor, 💄 UI, 📬 API

#185 수익 지출 관리 페이지 카테고리 렌더링 로직 수정
  src/containers/HistoryFormContainer.js
Labels: ⛰️ Epic

#186 머니로그 커뮤니티로 공유하기 기능 추가
  src/components/common/WriteActionButtons.js
  src/containers/MoneyLogContainer.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ✨ Feature, ⛰️ Epic

#187 배포 상태의 머니로그 api 경로 수정
  src/lib/api/moneylog.js
Labels: 🐞 BugFix

#188 머니로그 커뮤니티 공유 기능 수정
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ⛰️ Epic, ♻️ Refactor

#189 수익지출 관리 페이지 UI 수정
  src/containers/HistoryMainContainer.js
Labels: 🔨 Task, 💄 UI

#190 게시물 수정 기능 코드 원상복구
  src/containers/PostDetailContainer.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ♻️ Refactor

#191 머니로그 커뮤니티 공유하기 기능 수정
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ⛰️ Epic, ♻️ Refactor

#192 자산관리 목표 api, 예산 GET api, 지출비율 GET api 적용
  src/components/FinancialLedger/MoneyLogAssetGoal.js
  src/containers/BudgetContainer.js
  src/containers/ExpenseContainer.js
  src/containers/HistoryMainContainer.js
  src/lib/api/setting.js
  src/pages/FinancialLedgerPage/index.js
Labels: 🔨 Task, 📬 API

#194 머니로그 공유하기 기능 수정 및 UI 수정
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogAssetGoal.js
  src/components/common/Editor.js
  src/components/common/ImageList.js
  src/components/common/ImagePreview.js
  src/containers/MoneyLogContainer.js
  src/lib/api/post.js
  src/modules/post.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI, 📬 API

#196 머니로그 페이지 UI 수정
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogGuide.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
Labels: 🔨 Task, 💄 UI

#197 비로그인 시 나타나는 가계부 UI와 커뮤니티 UI 수정
  src/components/Community/PostItem.js
  src/components/common/Header/UserLinks.js
  src/components/common/NotLogin.js
  src/pages/FinancialLedgerPage/index.js
Labels: ⛰️ Epic, 💄 UI

#198 커뮤니티 api 요청 이후 로직 수정
  src/containers/PostDetailContainer.js
  src/pages/CommunityPage/CommunityListPage.js
  src/pages/CommunityPage/CommunityWritePage.js
Labels: ⛰️ Epic, ♻️ Refactor

#199 게시물 수정 기능 코드 수정
  src/pages/CommunityPage/CommunityWritePage.js
Labels: 🐞 BugFix

#200 수익지출 관리 페이지 UI 수정 및 그에 따른 api 적용 코드 수정
  src/components/FinancialLedger/HistoryForm.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/components/FinancialLedger/HistoryMainList.js
  src/containers/HistoryFormContainer.js
Labels: ⛰️ Epic, ♻️ Refactor

#201 useQuery retry 옵션 false에서 1로 수정
  src/containers/HistoryMainContainer.js
  src/containers/MoneyLogContainer.js
Labels: ♻️ Refactor, 📬 API

#202 자산관리 목표 UI 수정
  src/components/FinancialLedger/MoneyLogAssetGoal.js
Labels: 🔨 Task, 💄 UI

#203 머니로그 페이지 수익지출 목록 UI 수정
  src/components/FinancialLedger/MoneyLogGuide.js
Labels: 🔨 Task, 💄 UI

#204 커뮤니티 및 머니로그 글에서 link부분 자동으로 하이퍼링크로 처리
  src/components/Community/PostDetail.js
  src/components/FinancialLedger/MoneyLog.js
  src/lib/index.js
Labels: ⛰️ Epic, ♻️ Refactor

#205 링크 자동 삽입 함수 코드 누락 수정
  src/lib/utils.js
Labels: 🐞 BugFix

#193 마이페이지 중 개인정보 변경 UI 변경
  src/App.js
  src/components/MyPage/PersonalInfoChangeForm.js
Labels: ⛰️ Epic, ♻️ Refactor, 💄 UI

#207 머니로그 페이지 드롭박스 UI 수정
  src/components/FinancialLedger/MoneyLog.js
Labels: 🔨 Task, 💄 UI

#208 반응형 웹 디자인 적용
  src/components/Community/PostItem.js
  src/components/FinancialLedger/HistoryForm.js
  src/components/FinancialLedger/HistoryMain.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogGuide.js
  src/components/FinancialLedger/StyledComponentInSetting.js
  src/components/common/Calender.js
  src/components/common/Header/UserLinks.js
  src/components/common/ImageList.js
  src/components/common/SideBar.js
  src/containers/HistoryFormContainer.js
  src/containers/HistoryMainContainer.js
  src/lib/api/statistic.js
  src/pages/CommunityPage/index.js
  src/pages/FinancialLedgerPage/FinancialLedgerSubPage.js
  src/pages/FinancialLedgerPage/HistoryPage.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
  src/pages/FinancialLedgerPage/SettingPage.js
  src/pages/FinancialLedgerPage/index.js
Labels: ⛰️ Epic, 💄 UI

#209 통계 페이지 UI 구현 및 api 적용
  src/components/FinancialLedger/ComparisonModal.js
  src/components/FinancialLedger/MonthStatistic.js
  src/components/FinancialLedger/StatisticStyled.js
  src/components/FinancialLedger/WeekStatistic.js
  src/components/FinancialLedger/YearStatistic.js
  src/components/MyPage/MyCommetItem.js
  src/components/MyPage/MyPostItem.js
  src/components/common/BarGraph.js
  src/components/common/Calender.js
  src/constants/calender.js
  src/constants/category.js
  src/constants/community.js
  src/constants/index.js
  src/lib/api/statistic.js
  src/lib/utils.js
  src/pages/FinancialLedgerPage/StatisticPage.js
  src/pages/FinancialLedgerPage/index.js
Labels: 🔨 Task, 💄 UI, 📬 API

#210 모달 컴포넌트 state control로 수정
  src/components/FinancialLedger/SetCategory.js
  src/components/FinancialLedger/SetExpenseRatio.js
  src/components/FinancialLedger/SetMonthlyBudget.js
  src/components/Login/LoginModal.js
  src/components/common/DoubleCheckModal.js
  src/components/common/Header/UserLinks.js
  src/components/common/Modal.js
  src/components/common/NotLogin.js
Labels: 🔨 Task, 💄 UI

#211 마이페이지 및 수익 지출 관리 페이지에 반응형 웹 디자인 적용
  src/components/Community/PostDetail.js
  src/components/FinancialLedger/HistoryForm.js
  src/components/FinancialLedger/HistoryMainItem.js
  src/components/FinancialLedger/HistoryMainList.js
  src/components/FinancialLedger/MoneyLog.js
  src/components/FinancialLedger/MoneyLogForm.js
  src/components/FinancialLedger/MoneyLogGuide.js
  src/components/MyPage/MyPostList.js
  src/components/MyPage/NoList.js
  src/components/common/SideBar.js
  src/containers/HistoryFormContainer.js
  src/containers/PostDetailContainer.js
  src/modules/history.js
  src/pages/FinancialLedgerPage/HistoryPage.js
  src/pages/FinancialLedgerPage/MoneyLogPage.js
  src/pages/MyPage/index.js
Labels: ⛰️ Epic, 💄 UI

#214 html2canvas 패키지 설치
  package-lock.json
  package.json
Labels: 📦️Package

#215 통계 공유하기 기능 추가
  src/components/FinancialLedger/ComparisonModal.js
  src/components/FinancialLedger/MonthStatistic.js
  src/components/FinancialLedger/StatisticStyled.js
  src/components/FinancialLedger/WeekStatistic.js
  src/components/FinancialLedger/YearStatistic.js
  src/components/common/BarGraph.js
  src/components/common/ImageList.js
  src/constants/index.js
  src/containers/StatisticContainer.js
  src/lib/utils.js
  src/modules/post.js
  src/pages/FinancialLedgerPage/StatisticPage.js
Labels: ✨ Feature, ⛰️ Epic

#216 마이페이지 UI 수정
  src/components/MyPage/MyPostList.js
  src/components/MyPage/NoList.js
Labels: 🔨 Task, 💄 UI

#217 게시글 삭제 시 refetch하도록 수정
  src/containers/PostDetailContainer.js
Labels: 🐞 BugFix
